- name: Authenticate and execute a command in Openshift Container Platform
  hosts: localhost
  module_defaults:
    group/commnuity.okd.okd:
      host: https://api.crc.testing:6443
      validate_certs: false
  tasks:
    - name: Authenticate to OpenShift cluster and gell a list of all pods from any namespace
      block:
        - name: Include 'openshift_passwords.yml'
          ansible.builtin.include_vars: openshift_passwords.yml

        - name: Log in (obtain access token)
          community.okd.openshift_auth:
            username: developer
            password: developer
          register: openshift_auth_results

        - name: Get a list of all deploy from any namespace
          kubernetes.core.k8s_info:
            api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
            kind: Deployment
            namespace: gcds-new
          register: pod_list

        - name: Execute a command in a specific pod
          kubernetes.core.k8s_exec:
            api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
            namespace: gcds-new
            pod: gcds-775b8b45f8-lnhvv
            command: 'echo "Hello This was executed from a AAP tempalte/playbook (Basic Command)"'
            container: gcds
          register: exec_results

        - name: Print the output of the command executed in the pod
          ansible.builtin.debug:
            msg: "Command output: {{ exec_results.stdout }}"


      always:
        - name: If login succeeded, try to log out (revoke access token)
          when: openshift_auth_results.openshift_auth.api_key is defined
          community.okd.openshift_auth:
            state: absent
            api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
